from openai import OpenAI
from rest_framework.decorators import api_view
from rest_framework.response import Response


@api_view(["POST"])
def chat(request):
    message = request.data.get("message")  # text typed by the user on the frontend
    if not message:
        return Response({"error": "message is required"}, status=400)

    client = OpenAI(
        base_url="http://localhost:11434/v1",
        api_key="ollama",
    )  # reads OPENAI_API_KEY from the environment
    llm_response = client.responses.create(
        model="smollm2:135m-instruct-q2_K",  # small, cheap model - fine for learning
        input=message,
    )

    return Response({"reply": llm_response.output_text})  # text generated by the model
